### PR TITLE
fix issue #29

### LINKED ISSUE #29: book opening to be "debounced"
If I tap quickly several times on a cover, the book seems to "stack", be opened several times, one book appearing over the other. If I use the back action, the book isn't closed, but I "come back" to the "book below".

### PR DESCRIPTION
**Pull request by iaomw**
fixes #29

This PR fixed issue #29 by disable user interaction while loading book asynchronizly, then re-enable it after the loading task. It also added a little visual indicator for loading. 

I will replace the loading indicator later with other PR. It should be treated as enhancement. Consider the loading process of LCP book, it also need some visual indicator.

### CODE REVIEW

File: r2-testapp-swift/LibraryViewController.swift [hunk 1]
```diff
@@ -183,24 +189,57 @@ extension LibraryViewController: UICollectionViewDelegateFlowLayout {
...
+            
+        }) { (message) in
+            
+            cleanup()
+            self.infoAlert(title: "Error", message: message ?? "")
+        }
+    }
+    
+    func loadPublication(publication: Publication,
+                         succ: ((UIViewController)->Void)? = nil,
```
Comment (aferditamuriqi) [inline r2-testapp-swift/LibraryViewController.swift]: can we name this "success" instead of shortening it to "succ"

File: r2-testapp-swift/LibraryViewController.swift [hunk 2]
```diff
@@ -277,4 +316,17 @@ extension LibraryViewController: PublicationCellDelegate {
...
 
-
+class PublicationIndicator: UIActivityIndicatorView {
+    override func didMoveToSuperview() {
+        super.didMoveToSuperview()
+        
+        guard let superView = self.superview else {return}
+        self.translatesAutoresizingMaskIntoConstraints = false
+        
+        let hConstraint = NSLayoutConstraint(item: self, attribute: .centerX, relatedBy: .equal, toItem: superView, attribute: .centerX, multiplier: 1.0, constant: 0.0)
```
Comment (aferditamuriqi) [inline r2-testapp-swift/LibraryViewController.swift]: I would prefer horizontalConstrain instead of hConstraint

File: r2-testapp-swift/LibraryViewController.swift [hunk 3]
```diff
@@ -277,4 +316,17 @@ extension LibraryViewController: PublicationCellDelegate {
...
+        
+        let vConstraint = NSLayoutConstraint(item: self, attribute: .centerY, relatedBy: .equal, toItem: superView, attribute: .centerY, multiplier: 1.0, constant: 0.0)
```
Comment (aferditamuriqi) [inline r2-testapp-swift/LibraryViewController.swift]: same here I would prefer verticalConstrain instead of vConstraint

File: r2-testapp-swift/LibraryViewController.swift [hunk 4]
```diff
@@ -183,24 +189,57 @@ extension LibraryViewController: UICollectionViewDelegateFlowLayout {
...
+        }
+    }
+    
+    func loadPublication(publication: Publication,
+                         succ: ((UIViewController)->Void)? = nil,
+                         fail: ((String?)->Void)? = nil) {
+        
+        // Get publication type
+        
+        let pubType = PublicationType(rawString: publication.internalData["type"])
```
Comment (aferditamuriqi) [inline r2-testapp-swift/LibraryViewController.swift]: pubType is probably fine, but we can also write it out to publicationType. in general we should not shorten when possible any variables or methods etc.

**Comment by aferditamuriqi** [comment]
I will need more time to review this PR, as there were changes in addition to my comments. it would be great to have new additions separated and commented instead of just added to a completed review.

File: r2-testapp-swift/LibraryViewController.swift [hunk 5]
```diff
@@ -316,17 +307,40 @@ extension LibraryViewController: PublicationCellDelegate {
...
+class PublicationIndicator: UIView  {
+    
+    lazy var indicator: UIActivityIndicatorView =  {
+        
+        let result = UIActivityIndicatorView(activityIndicatorStyle: UIActivityIndicatorViewStyle.whiteLarge)
+        result.translatesAutoresizingMaskIntoConstraints = false
+        self.backgroundColor = UIColor(white: 0.3, alpha: 0.7)
+        self.addSubview(result)
+        
+        let hConstraint = NSLayoutConstraint(item: result, attribute: .centerX, relatedBy: .equal, toItem: self, attribute: .centerX, multiplier: 1.0, constant: 0.0)
```
Comment (aferditamuriqi) [inline r2-testapp-swift/LibraryViewController.swift]: I would prefer horizontalConstrain instead of hConstraint

File: r2-testapp-swift/LibraryViewController.swift [hunk 6]
```diff
@@ -316,17 +307,40 @@ extension LibraryViewController: PublicationCellDelegate {
...
+        let vConstraint = NSLayoutConstraint(item: result, attribute: .centerY, relatedBy: .equal, toItem: self, attribute: .centerY, multiplier: 1.0, constant: 0.0)
```
Comment (aferditamuriqi) [inline r2-testapp-swift/LibraryViewController.swift]: I would prefer verticalConstrain instead of vConstraint

File: r2-testapp-swift/LibraryViewController.swift [hunk 7]
```diff
@@ -29,6 +29,12 @@ class LibraryViewController: UICollectionViewController {
     var publications: [Publication]
     weak var delegate: LibraryViewControllerDelegate?
     weak var lastFlippedCell: PublicationCell?
+    
+    lazy var loadingIndicator: PublicationIndicator = {
+        
+        let indicator = PublicationIndicator()
+        return indicator
+    } ()
```
Comment (aferditamuriqi) [inline r2-testapp-swift/LibraryViewController.swift]: can we achieve the same with this line?
`lazy var loadingIndicator: PublicationIndicator = PublicationIndicator()`
